# .neetoci/playwright-nightly-staging.yml

version: v1.0

fail_fast: false
is_cypress: true
parallelism: 4
plan: professional-2

envs:
  - key: TEST_ENV
    value: staging
  - key: DEPLOYMENT_URL
    value: http://www.neeto.com/neetodesk?env=staging

global_job_config:
  setup:
    - checkout
    - neetoci-version node 18.12
    - cache restore
    - yarn install
    - cd playwright-tests
    - yarn install
    - yarn playwright install --with-deps
    - cache store
  jobs:
    - name: Playwright Staging Nightly
      commands:
        - yarn playwright:ci --shard=$((${JOB_COMPLETION_INDEX}+1))/4

triggers:
  - event: cron
    cron_line: "0 3,15 * * MON,TUE,WED,THU,FRI"
    branch: main
