# .nnetoci/playwright-staging.yml

version: v1.0

fail_fast: false
is_cypress: true
parallelism: 4
plan: professional-2

envs:
  - key: TEST_ENV
    value: staging
  - key: DEPLOYMENT_URL
    value: http://www.neeto.com/neetdesk?env=staging

global_job_config:
  setup:
    - checkout
    - neetoci-version node 18.12
    - cache restore
    - yarn install
    - cd playwright-tests
    - yarn install
    - yarn playwright install --with-deps
    - cache store
  jobs:
    - name: Playwright Staging
      commands:
        - yarn playwright:ci --shard=$((${JOB_COMPLETION_INDEX}+1))/4

lifecycle:
  on_running:
    - action: remove_labels
      labels: ["playwright-staging-completed", "playwright-staging-run"]
    - action: add_labels
      labels: ["playwright-staging-triggered"]

  on_complete:
    - action: remove_labels
      labels: ["playwright-staging-run", "playwright-staging-triggered"]
    - action: add_labels
      labels: ["playwright-staging-completed"]

triggers:
  - event: pull_request_labeled
    label: playwright-staging-run
