export const VIEW_SELECTORS = {
    settingsNavTab: 'settings-nav-tab',
    viewsSettingsOption: 'views-settings-option',
    settingsNewView: 'settings-new-view-button',
    nameField: 'name-input-field',
    viewsDescText: 'views-description-textarea',
    activeSwitch: 'active-switch',
    closeIcon: '[data-testid="close-icon"]',
    checkIcon: '[data-testid="check-icon"]',
    conditionFieldDropdownButton: 'condition-field-dropdown-button',
    conditionVerbDropdown: 'condition-verb-dropdown-button',
    conditionValueMultiSelect: 'condition-value-multi-select-field',
    addConditionButton: 'add-condition-button',
    logicOperatorButton: 'logic-operator-button',
    deleteConditionButton: 'delete-condition-button-1',
    previewCallbackButton: 'preview-callback-button',
    fieldSelectValueContainer: 'field-select-value-container',
    directionSelectValueContainer: 'direction-select-value-container',
    myselfRadioLabel: 'myself-radio-label',
    allAgentsRadioLabel: 'all-agents-radio-label',
    disabledBlock: 'disabled-block',
    descTextInput: 'description-text-input',
    nameInputEror: 'name-input-error',
    fieldSelectError: 'field-select-error',
    directionSelectError: 'direction-select-error',
    taxonomySettingsOption: 'taxonomy-settings-option',

}